app = "ultravanilla"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PORT = "8080"

[[mounts]]
  source = "ultravanilla"
  destination = "/app/package/data"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
    [services.ports.http_options]
      [services.ports.http_options.response]
        [services.ports.http_options.response.headers]
          fly-cache-status = false
          fly-request-id = false
          server = false
          via = false

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    [services.ports.http_options]
      [services.ports.http_options.response]
        [services.ports.http_options.response.headers]
          fly-cache-status = false
          fly-request-id = false
          server = false
          via = false
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "2s"
    grace_period = "1m0s"
